
/* 
=============================================
Simple Example: How to perturb data using SAS
=============================================

Destatis, 11/30/2018

*/


/* Specify the library (where you can find microdata or ptable and want to save the output) */
libname data "YOUR/PATH/";

/* Specify the path (where you can find the macros) */
%let path = YOUR/PATH/ ;


/* Import the required macros */
%include "&path./ckm_macros_destatis.sas" / lrecl=500;
%include "&path./ckm_macro_generate_record_key.sas" / lrecl=500;

/* Import the multilabel (needed for the test hypercube) */
%include "&path./example_hc_9_2_multilabel.sas" / lrecl=500;


/* Attach record key to Microdata */
%ckm_generate_record_key(inputfile=data.hc_9_2_synth_microdata, outputfile=data.hc_9_2_synth_rkey, rkey=myrkey, seed=123456);

/* Aggregation of Microdata using a modified proc summary (IMPORTANT: aggregation of the record keys to cell keys!!) */
%ckm_summary(input=data.hc_9_2_synth_rkey, output=data.hc_9_2_synth_table, table_var=geo_m sex age_m yae_h, cfreq=count, rkey=myrkey, ckey=myckey);

/* Import Perturbation Table (generated by R-package "ptable" using type="destatis" and pt_export(..., tools="SAS").) */
%ckm_import_ptable(csvfile=&path./ptable_d2_v108_js1.csv, output=data.ptable_d2_v108_js1);

/* Perturbation of the data */
%ckm_perturbation(input=data.hc_9_2_synth_table, table_var=geo_m sex age_m yae_h, cfreq=count, ckey=myckey, ptable=data.ptable_d2_v108_js1, ckmlabel=perturbed);



